#!/bin/sh

if [ $(pidof hildonevents) ]
    then
        run-standalone.sh dbus-send --print-reply --dest=org.hildon.eventfeed.ui /org/hildon/eventfeed/ui org.hildon.eventfeed.ui.showWidget
    else
        run-standalone.sh /opt/hildonevents/bin/hildonevents "--widget"
fi
